from src.state.state import State

class BasicChatbot:
    """
    Class to handle the basic chatbot functionality.
    """

    def __init__(self, model):
        """
        Initialize the BasicChatbot with the given model.
        
        :param model: The LLM to be used for the chatbot.
        """
        self.model = model

    def process(self, state):
        """
        Process the state to generate a response from the model.
        
        :param state: The current state of the chatbot.
        :return: The response generated by the model.
        """
        
        return {'messages': self.model.invoke(state['messages'])}
       