name: Sync to Hugging Face Space
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab 
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required for history rewriting

      - name: Install git-filter-repo
        run: pip install git-filter-repo

      - name: Remove large file from history
        run: git filter-repo --path "Rag_Documents/layout-parser-paper.pdf" --invert-paths --force

      - name: Log in to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install -U "huggingface_hub>=0.20.0"
          huggingface-cli login --token $HF_TOKEN

      - name: Push to hub
        run: git push --force https://bpratik:$HF_TOKEN@huggingface.co/spaces/bpratik/Chatbot main